### ISSUE TITLE
powerup system

### ISSUE THREAD

**Issue by thejacer87** [thejacer87/AM1R#17]

**Comment by thelabcat** [comment]
This "report" is useless. "Powerup system"? What in the entire cyber universe is that supposed to mean? You didn't even take the trouble to say that it was broken, let alone in what way.

**Comment by thejacer87** [comment]
> This "report" is useless. "Powerup system"? What in the entire cyber universe is that supposed to mean? You didn't even take the trouble to say that it was broken, let alone in what way.

Sir, this is a Wendy's.

Your must be lost on the internet lol.

This is my project buddy, I'm just keeping notes for myself.

Cheers

**Comment by thelabcat** [comment]
> This is my project.

I'm sorry, I didn't know. In my defense, if anyone else filed an issue like that on a responsory, I'm sure you would not appreciate it. I had kind of a bad day with technical stuff, I'm sorry if I was overly terse.

**Comment by thejacer87** [comment]
Sure, I wouldn't appreciate it. But I wouldn't lash out on some random repository that I have nothing to with.

I'm not sure how or why you got notified of my issue on this repo, but you didn't need to respond regardless.

Hope you figure stuff out.

**Comment by thelabcat** [comment]
I got notified because I follow it out of personal interest. I was trying to be helpful to you, since if someone filed an issue on my repository with zero details I would have wanted someone to try and get them and save me time. I possibly should have paid more attention to the user badges, or really just not been talking when I knew I was upset, so I'm sorry for the strife.
